# Site settings
name: Math and Pencil 
title: 
email: info@mathandpencil.com
description: "Bringing Your Ideas To Life"
url: "https://www.mathandpencil.com"
username: "mathandpencil"

# Build settings
markdown: kramdown
permalink: /:title
baseurl: "http://blog.mathandpencil.com"
